language: python
services:
  - docker
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
before_install:
  - docker pull vlsida/openram-ubuntu:latest
  - docker run vlsida/openram-ubuntu:latest  /bin/sh -c "source setpaths.sh && python3 compiler/tests/regress.py"
  - docker ps -a
# command to run tests
script:
  - source setpaths.sh && python3 compiler/tests/regress.py
