language: python
#services:
#  - docker
#before_install:
#- docker pull vlsida/openram
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - source set_paths.sh && python3 compiler/tests/regress.py
  - python3 compiler/tests/regress.py